### ISSUE TITLE
ToDo's for v0.14

### ISSUE THREAD

**Issue by AndreMaz** [moleculerjs/site#70]
Sticky placeholder to keep track of [things](https://github.com/moleculerjs/moleculer/blob/next/CHANGELOG.md) we need to update in the docs:

- [ ] communication protocol changed (`3` -> `4`)
- [x] handling conflict nodeIDs
- [x]  **Breaking**: `validation` broker options is removed. Use `validator` instead. If `validator` is defined or `true`, the validation is enabled. Otherwise, it is disabled.
- [ ] `ctx` access in Strategies `next` method.
- [x] Shard strategy is added.
    ```js
	const broker = new ServiceBroker({
		registry: {
			strategy: "Shard",
			strategyOptions: {
				shardKey: "name"
			}
		}
	});
    ```
- [x] The `broker.use` deprecated method is removed. Use `middlewares: []` in the broker options instead.
- [x] hooks inside action definitions, as well.
    ```js
    broker.createService({
        name: "greeter",
        hooks: {
            before: {
                "*"(ctx) {
                    broker.logger.info(chalk.cyan("Before all hook"));
                },
                hello(ctx) {
                    broker.logger.info(chalk.magenta("  Before hook"));
                }
            },
            after: {
                "*"(ctx, res) {
                    broker.logger.info(chalk.cyan("After all hook"));
                    return res;
                },
                hello(ctx, res) {
                    broker.logger.info(chalk.magenta("  After hook"));
                    return res;
                }
            },
        },

        actions: {
            hello: {
                hooks: {
                    before(ctx) {
                        broker.logger.info(chalk.yellow.bold("    Before action hook"));
                    },
                    after(ctx, res) {
                        broker.logger.info(chalk.yellow.bold("    After action hook"));
                        return res;
                    }
                },

                handler(ctx) {
                    broker.logger.info(chalk.green.bold("      Action handler"));
                    return `Hello ${ctx.params.name}`;
                }
            }
        }
    });    
    ```

    **Output**
    ```
    INFO  - Before all hook
    INFO  -   Before hook
    INFO  -     Before action hook
    INFO  -       Action handler
    INFO  -     After action hook
    INFO  -   After hook
    INFO  - After all hook
    ```
- [x] broker `metadata` option. It's transfered to other nodes.
- [x] new middleware hooks (`registerLocalService`, `serviceCreating`, `transitPublish`, `transitSubscribe`, `transitMessageHandler`, `transporterSend`, `transporterReceive`) [#436](https://github.com/moleculerjs/moleculer/issues/436)
- [x] enhanced hot-reload middleware [#408](https://github.com/moleculerjs/moleculer/issues/408)
- [x] new Middlewares:
    - `Transmit.Encryption`
	- `Transmit.Compression`
    - `Debugging.TransitLogger`
    - `Debugging.ActionLogger`
    - ...etc

- [x] Kafka transporter upgrade to support kafka-node@4
- [x] rename `ctx.metrics` -> `ctx.tracing`
- [x] new built-in tracing solution with exporters (Zipkin, Jaeger, Datadog)
- [x] new built-in metrics solution with reporters (Prometheus, Datadog, StatD)
- [x] extend internal services (`$node`)
    ```js
    // moleculer.config.js
    module.exports = {
        nodeID: "node-1",
        logger: true,
        internalServices: {
            $node: {
                actions: {
                    // Call as `$node.hello`
                    hello(ctx) {
                        return `Hello Moleculer!`;
                    }
                }
            }
        }
    };
    ```

- [x] load middlewares by names
    ```js
        const { Middlewares } = require("moleculer");

        // Extend with custom middlewares
        Middlewares.MyCustom = {
            created(broker) {
                broker.logger.info("My custom middleware is created!");
            }
        };


        const broker1 = new ServiceBroker({
            logger: true,
            middlewares: [
                // Load by middleware name
                "MyCustom"
            ]
        });    
    ```
Please note: middleware must be `Object`. If `Function` it will be called with `broker`. Previous backward compatibility is dropped.

- [x] global errorHandler in ServiceBroker `errorHandler(err, info) {}`
    - in `info` can be reachable actual service or context or action or event...
    - if the error handled, not printed to the console or throw further.
    
- [x] `broker.hotReloadService` has been removed.

**Comment by icebob** [comment]
I will fill more details every point in the changelog.
